### ISSUE TITLE
Add instructive examples

### ISSUE THREAD

**Issue by krischer** [DavideNardone/MTSS-Multivariate-Time-Series-Sofwtare#13]
There are some examples in the readme but at least one of them (see answer in the functionality section) does not work. Furthermore it is not explained what these examples actually are or what the expected result should be. As mentioned before I don’t really see how to get the results.

Part of a review at: https://github.com/openjournals/joss-reviews/issues/1049

**Comment by DavideNardone** [comment]
All the example provided are now fully working! I have now committed a better explanation about the two tasks in the README. Furthermore, after adding the API documentation, the people interested in using the software have all the information to separately run the functions in the `module.cu`. As a plus (like stated by you on #9) i will also add some more instructive examples.
