### ISSUE TITLE
Add proper debug mode

### ISSUE THREAD

**Issue by krischer** [DavideNardone/MTSS-Multivariate-Time-Series-Sofwtare#15]
“Debug mode” currently consists of a lot of commented sections `printX()` and so on. Please consider adding a proper compile option for it - this will ease the job of everyone looking at the code at a future point in time.

Part of a review at: https://github.com/openjournals/joss-reviews/issues/1049

**Comment by DavideNardone** [comment]
I added a `verbose mode` for displaying some information during the running
