### ISSUE TITLE
Standard directory structure

### ISSUE THREAD

**Issue by krischer** [DavideNardone/MTSS-Multivariate-Time-Series-Sofwtare#18]
Consider following the standard directory structure of `include`, `src`, …

Part of a review at: https://github.com/openjournals/joss-reviews/issues/1049

**Comment by karlrupp** [comment]
The build instructions need to be updated accordingly. With source and include directories separated, a proper build tool comes in handy, cf. https://github.com/DavideNardone/MTSS-Multivariate-Time-Series-Software/issues/16

**Comment by DavideNardone** [comment]
Bug fixed
