### ISSUE TITLE
TODO comment

### ISSUE THREAD

**Issue by krischer** [DavideNardone/MTSS-Multivariate-Time-Series-Sofwtare#21]
Line 26 and 27 of `module.cu`:

```cuda
//not working (must be changed)
__device__ float stdDev(float *data, int n,float *avg)
``` 

- maybe check this again?

Part of a review at: https://github.com/openjournals/joss-reviews/issues/1049

**Comment by DavideNardone** [comment]
That comment is old. However, some functions in the `module.cu` was neither updated or used in the software. I haven't removed them because someone may want to use it.
