### ISSUE TITLE
Why is WS a compile time parameter?

### ISSUE THREAD

**Issue by krischer** [DavideNardone/MTSS-Multivariate-Time-Series-Sofwtare#23]
I don’t see a convincing reason why `WS` must be specified at compile time. The code would be more flexible if this is a runtime variable. But maybe I am missing something. Please clarify or make it a runtime option.

Part of a review at: https://github.com/openjournals/joss-reviews/issues/1049

**Comment by DavideNardone** [comment]
Compiling the sources code with the STATIC variable `WS` makes the CUDA software run faster. 
Knowing a priori the length of the the time serie allows us to allocate the support matrix T directly into the registers of the CUDA's blocks where the access to it by the threads is either much faster than the shared memory or global.
Moreover, the algorithm is optimized to work only on a subset of the matrix `T`, that is `array[WS][2]` 
(which is updated at each iteration) and therefore there is no problem of allocation of this structure into the registers that are much smaller than the other device memories.

![cuda-memory-model-nvidia-2007](https://user-images.githubusercontent.com/13561546/48705881-be307c00-ebfa-11e8-9ba9-ac2357556eef.png)

**Comment by karlrupp** [comment]
I've got the same question. Following your argument, every linear algebra library would only allow for squared matrices of size e.g. 128x128 because that happens to be good for caches.

The recommended approach is to make WS a runtime parameter and then dispatch between optimized/fallback implementations as needed. With a bit of metaprogramming you can auto-generate the different kernels.

Part of a review at: https://github.com/openjournals/joss-reviews/issues/1049

**Comment by DavideNardone** [comment]
I am sorry but the software has been thought and optimized from the beginning to work with the `WS` static variable. All kernels take into account the using of that variable, therefore changing it would mean changing all the logic implemented into the software.

**Comment by karlrupp** [comment]
You can pass WS as a template argument and do the dispatch outside the kernels :-)

**Comment by DavideNardone** [comment]
As far as I know, a static variable cannot be compiled at runtime. The following data_structure `float array[WS][2]` relies on `WS` variable to make the access to memory faster. If there's a way to bypass it I don't have any clue about it.

**Comment by karlrupp** [comment]
For example:
```
switch (runtime_ws) {
case 8:  optimized_kernel<8>(args);
case 16:  optimized_kernel<16>(args);
case 32:  optimized_kernel<32>(args);
case 64:  optimized_kernel<64>(args);
case 128:  optimized_kernel<128>(args);
default: fallback_kernel<96>(args);
}
```
where the template parameter is the 'static' WS (this snippet is of course just a first rough outline).

There's also the option to just-in-time compile CUDA kernels in CUDA 8 (I think) and above.

**Comment by DavideNardone** [comment]
By trying this approach i get (obviously) this error: `source/module.cu(312): error: expression must have a constant value`. I don't think it's possible to do what you suggested....

**Comment by karlrupp** [comment]
What is the kernel function declaration that you've tried?

**Comment by DavideNardone** [comment]
Sorry my bad! It compile as long as the the kernel function definition is included in the header file... For example, given the following files:

**test2.h**
```
#ifndef HEADER_H
#define HEADER_H

#ifdef __cplusplus
extern "C" {
#endif

template<int >
__global__ void kernel();

#ifdef __cplusplus
}
#endif

#endif
```
**test2.cu**
```
#include "test2.h"

using namespace std;

template<int action>
__global__ void kernel()
{
	// printf("%d\n",action);
    for(int i=0; i < action; ++i) {}

	float array[action][2];

}
```

**test.cu**
```
#include <stdlib.h>
#include <stdio.h>
#include <sys/time.h>
#include <cuda.h>
#include <unistd.h>

#include "test2.h"

int main(int argc, char **argv) {

    float grid_size;
    dim3 grid;
    dim3 threads;

    grid_size = ceil((float)100 / 2);

    grid.x = grid_size;
    grid.y = 1;
    threads.x = 10;
    threads.y = 1;

	int ws_runtime = atoi(argv[1]);
	printf("%d\n", ws_runtime);

	kernel<2><<<grid, threads>>>();
}
```

When i run `nvcc test.cu test3.cu -o test` i get the following error:

_test2.h(20): error: this declaration may not have extern "C" linkage_

Plus, I still cant find _just-in-time_ compile CUDA kernels but i suppose it will allow the following instruction `optimized_kernel<ws_runtime>(args);` to be compiled at run-time.
 In case the latter couldn't be possible i think it's craziness to hard-code all the `WS` possible parameters which theoretically could be infinite.

**Comment by karlrupp** [comment]
Template functions don't have external linkage. You'd have to explicitly instantiate the respective instantiations in the test2.cu file. This is not CUDA-specific; you'd have the same problem with normal C++ sources.

A simple fix is to move the kernel launch into the same file as the kernel.

You don't need to hard-code all possible WS-parameters, but you will need a reasonable strategy for selecting suitable WS sizes. For example, you can always choose the next power of 2 (maybe plus or minus 1 to avoid bank conflicts) for WS. This way all choices for WS from 65...127 map to WS=128 in the "infinite" range of parameters for WS becomes all of a sudden very small.

**Comment by DavideNardone** [comment]
If i got you right, you're suggesting me to map range of `WS` parameters into different template kernels.
Let's hypotize I run the software with `ws_runtime=520` which would then call the `optimized_kernel<1024>(args)`. By doing this, I would allocate the data_structure `float array[ws][2]` with `ws=1024` which i think would result in a wasting `2x504` memory locations.

Do you think is worth wasting memory instead of including a static variable?
