### ISSUE TITLE
variable length input

### ISSUE THREAD

**Issue by Akanksha2511** [DavideNardone/MTSS-Multivariate-Time-Series-Sofwtare#28]
Hi, 

The software looks very good but as I understand it does not work for unequal length signals. Is it possible to add this functionality in the future release? Or some way I can use it with variable length signals. 

Thanks, 
Akanksha

**Comment by DavideNardone** [comment]
Hi,

yes, it works only on equal variables length. I am sorry but this features is not going to be added in any new feature release. Feel free to fork the repository and add it.
