### ISSUE TITLE
Fix installation readme

### ISSUE THREAD

**Issue by krischer** [DavideNardone/MTSS-Multivariate-Time-Series-Sofwtare#3]
The current readme clones the repository and then specifies to unzip the `master.zip` file. This is inconsistent - please fix it.

See https://github.com/openjournals/joss-reviews/issues/1049

**Comment by DavideNardone** [comment]
I've replaced the previous two commands with the following one: 
`git clone https://github.com/DavideNardone/MTSS-Multivariate-Time-Series-Sofwtare.git <target>`
and therefore updated the README file.
