### ISSUE TITLE
Output different on CPU and GPU

### ISSUE THREAD

**Issue by krischer** [DavideNardone/MTSS-Multivariate-Time-Series-Sofwtare#6]
```bash
# Classification CPU
time ./mdtwObj -t CLASSIFICATION -i CPU 3 1 \
    -f data/classification/rm_1/X_MAT data/classification/rm_1/Y_MAT data/classification/rm_1/Z_MAT \
    -k 10 -o 1000 152 -m 0 DTW 2>&1 | tee classification_CPU.txt

# Classification GPU
time ./mdtwObj -t CLASSIFICATION -i GPU 3 512 1 \
    -f data/classification/rm_1/X_MAT data/classification/rm_1/Y_MAT data/classification/rm_1/Z_MAT \
    -k 10 -o 1000 152 -m 0 DTW -d 0 2>&1 | tee classification_GPU.txt
```

These examples from the readme don't have the same results.

Results: 

[classification_CPU.txt](https://github.com/DavideNardone/MTSS-Multivariate-Time-Series-Software/files/2573790/classification_CPU.txt)
[classification_GPU.txt](https://github.com/DavideNardone/MTSS-Multivariate-Time-Series-Software/files/2573791/classification_GPU.txt)

For some reason the results for the CPU and GPU versions do not match. I did not look why this is the case. If there is some random component please allow the users to set the initial state of the RNG to get reproducible results.

Part of a review at: https://github.com/openjournals/joss-reviews/issues/1049

**Comment by DavideNardone** [comment]
As you said, a component of the software(the K-Fold Cross Validation) includes a random component which causes the GPU and CPU versions to get different results on the same initial dataset. I've identified the function who triggers that behavior and i'll fix it by adding a _shuffle_flag_ on the command line( e.g., -k 10 <0,1>) which will allow the user to get reproducible results.

**Comment by krischer** [comment]
Great. You don't need to close issues manually - you can just include `closes #6` in a commit message to master and the issue will be closed with a reference to the commit fixing it - that way it is easier to follow. The same works with pull requests if you prefer that workflow.

**Comment by DavideNardone** [comment]
@krischer I've just read it. Thank you for the advice ;)

**Comment by karlrupp** [comment]
I encounter similar reproducibility issues:

```
$> ./mdtwObj -t CLASSIFICATION -i CPU 3 1 -f data/classification/rm_1/X_MAT data/classification/rm_1/Y_MAT data/classification/rm_1/Z_MAT -k 10 0 -o 1000 152 -m 0 DTW -v 0

The number of iteration is greater than testSize! Verbose mode will be suppressed for this run
Reading data...
Dataset size: [1000,152,3]

Classification w/ DEPENDENT-DTW using CPU

Regular Accuracy mean is 53.967915
The Error rate mean of NR is 0.460321

$> ./mdtwObj -t CLASSIFICATION -i GPU 3 512 1 -f data/classification/rm_1/X_MAT data/classification/rm_1/Y_MAT data/classification/rm_1/Z_MAT -k 10 0 -o 1000 152 -m 0 DTW -d 0 -v 0

The number of iteration is greater than testSize! Verbose mode will be suppressed for this run
Reading data...
Dataset size: [1000,152,3]

Classification w/ DEPENDENT-DTW using GPU

Regular Accuracy mean is 4.352184
The Error rate mean of NR is 0.956478
```

**Comment by DavideNardone** [comment]
Well I do not (see attached files). You maybe compiled the sources with `WS` parameter different than 152. Anyway I will add a check on both parameters to make sure they are identical.

[repoducibility_CPU.txt](https://github.com/DavideNardone/MTSS-Multivariate-Time-Series-Software/files/2623643/repoducibility_CPU.txt)
[repoducibility_GPU.txt](https://github.com/DavideNardone/MTSS-Multivariate-Time-Series-Software/files/2623644/repoducibility_GPU.txt)

**Comment by karlrupp** [comment]
Well, should a user really recompile the software for every example?

(In analogy, should I recompile my browser every time I want to go to a new webpage?)

**Comment by DavideNardone** [comment]
fixed
