### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by krischer** [DavideNardone/MTSS-Multivariate-Time-Series-Sofwtare#9]
There are currently no tests or reproducible examples right now. I recommend setting up some unit and integration testing and especially compare the results against some known good result. Integration into a CI service would also be a good idea.

Part of a review at: https://github.com/openjournals/joss-reviews/issues/1049

**Comment by DavideNardone** [comment]
I can provide some unit and integration test but i don't understand what you mean by the following sentence: _especially compare the results against some known good result?_ Could you please be more specif about it?

**Comment by jedbrown** [comment]
The reference is to *verification*: establishing that the code computes the mathematical quantity it claims to. One could choose special inputs such that the outputs are known without running your code. Alternatively, you could compare to outputs produced by some trusted community code.
